name: Pytest testing

on:
  push:
    branches:    
      - 'main'
      - 'dev'
      - 'automated_testing'
  pull_request:
    branches:
      - 'main'
      - 'dev'
      - 'automated_testing'

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.9', '3.10'] 
    steps:
    - uses: actions/checkout@v3

    - name: Free disk space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h

    - name: Set up Anaconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        channels: conda-forge, defaults
        use-only-tar-bz2: true
        auto-update-conda: true
        auto-activate-base: true

    - name: Create conda environment
      run: |
        echo "begin: PATH=$PATH;"
        conda create --name test_install python=${{ matrix.python-version }} -y

    - name: Install Excalibur
      run: |
        conda activate test_install || true
        python -m pip install --upgrade pip
        pip install -e .

    - name: Run tests
      run: |
        conda activate test_install || true
        pytest -rA
